-- phpMyAdmin SQL Dump
-- version 4.8.3
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Waktu pembuatan: 04 Jul 2020 pada 16.12
-- Versi server: 10.1.36-MariaDB
-- Versi PHP: 7.2.10

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `resep`
--

-- --------------------------------------------------------

--
-- Struktur dari tabel `masakan`
--

CREATE TABLE `masakan` (
  `id` int(11) NOT NULL,
  `Nama` varchar(20) NOT NULL,
  `pendahuluan` varchar(500) NOT NULL,
  `Resep` varchar(500) NOT NULL,
  `Cara` varchar(500) NOT NULL,
  `foto` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data untuk tabel `masakan`
--

INSERT INTO `masakan` (`id`, `Nama`, `pendahuluan`, `Resep`, `Cara`, `foto`) VALUES
(1, 'Ayam Bakar Kecap', '\"Tips untuk memasak ayam bakar yang enak adalah bara api dari arang jangan terlalu besar, agar ayam dapat matang merata dan kulit tidak gosong.\"\r\n\r\n    \"Jangan lupa oleskan sedikit mentega pada saat ayam dibakar agartidak lengket. Selain itu mentega juga dapat membuat aroma lebih harum dan rasa Iebih gurih. Lebih baik dibakar sesaat sebelum disajikan.\"\r\n', 'Bahan Utama:\r\n\r\n    \"-1 ekor ayam, potong menjadi 4 bagian 2 sendok teh garam\"\r\n    \"-1 buah jeruk nipis. peras aimya\"\r\n    \"-250 ml kaldu ayam\"\r\n    \"-2 sdm mentega\"\r\n\r\n    \"Bumbu\"\r\n    \"-7 butir bawang merah\"\r\n    \"-4 siung bawang putih\"\r\n    \"-1/2 sdt ketumbar\"\r\n    \"-1/2 sdt pala bubuk\"\r\n    \"-1/2 sdt merica\"\r\n    \"-1 sdt garam\"\r\n    \"-2 sdm minyak goreng\"\r\n    \"-5 sendok makan kecap manis\"\r\n\r\n    \"Sambal:\"\r\n    \"-5 sendok makan kecap manis\"\r\n    \"-3 buah cabai rawit iris tipis\"\r\n    \"-1 bua', '\"Cara Membuat\"\r\n    \"1. Cuci dan bersihkan ayam, kemudian potong menjadi 4 bagian\"\r\n    \"2. Lumuri dengan perasan air jeruk nipis dan garam. Diamkan sekitar 15 menit\"\r\n    \"3. Haluskan bawang merah, bawang putih dan ketumbar\"\r\n    \"4. Panas minyak dan tumis bumbu halus hingga harum, kemudian tambahkan pala bubuk, merica dan garam.\"\r\n    \"5. Masukkan potongan ayam kemudian tuangkan kaldu ayam dan tambahkan kecap manis, aduk rata. Ungkep hingga ayam menjadi empuk dan masak hingga kaldu habis. Angk', 'ayambkrkcp.jpg'),
(2, 'Ayam Cabe Ijo', '\" Untuk penyajiannya, ayam cabe ijo bisa disajikan bersama nasi putih hangat clan lalapan mentimun.\"\r\n\r\n    \".Bisa juga disajikan seperti di rumah makan padang; sajikan bersama rebusan daun singkong muda. Pasti akan membuat acara santap siang ataupun santap malam di rumah anda terasa sangat istimewa.\"', '\"Bahan Utama:\\n\"\r\n    \"-1 ekor ayam broiler, cuci bersih, potong 8 bagian\\n\"\r\n    \"-1 sdm air jeruk nipis\\n\"\r\n    \"-2 sdt garam\\n\"\r\n    \"-2 sdm minyak goreng untuk menumis\\n\"\r\n    \"-2 lembar daun jeruk\\n\"\r\n    \"-2 buah serai, memarkan pangkalnya\\n\\n\"\r\n\r\n    \"Bumbu Halus\\n\"\r\n    \"-8 butir bawang merah\\n\"\r\n    \"-5 siung bawang putih\\n\"\r\n    \"-10 buah cabai hijau besar\\n\"\r\n    \"-5 buah cabe rawit hijau besar\\n\"\r\n    \"-3 cm jahe\\n\"\r\n    \"-2 cm kunyit\\n\"\r\n    \"-3 butir kemiri\\n\"\r\n    \"-1 sdt garam\\n\"', '\"Cara Membuat\\n\\n\"\r\n    \"1. Lumuri potongan ayam dengan airjeruk nipis dan garam, sisihkan, niarkan selama 15 menit.\\n\"\r\n    \"2. Goreng ayam dalam minyak banyak hingga kuning kecokelatan.\\n\"\r\n    \"3. Tumis seluruh bumbu halus hingga harum dan matang, masukkan daun jeruk dan serai. Kemudian masukkan ayam goreng. Aduk hingga bumbu cabai hijau merata.\\n\"\r\n    \"4. Sajikan hangat.\\n\" \r\n', 'ayamcbeijo.jpg'),
(3, 'Bebek Goreng Cabe Ij', '\" Untuk penyajian yang Iebih berwarna, jangan lupa tambahkan daun selada, tomat, potongan jeruk lemon atau timun. Bahan-bahan pelengkap ini bisa anda sesuaikan dengan selera dan kebutuhan. Selamat mencoba\"', '\"Bahan Utama:\\n\"\r\n    \"-1 ekor bebek, cuci bersih, potong 4 bagian\\n\"\r\n    \"-2 sdm air jeruk nipis\\n\"\r\n    \"-1 butir asam kandis\\n\"\r\n    \"-2 sdt garam\\n\"\r\n    \"-2 sdm minyak goreng \\n\"\r\n    \"-2 lembar daun jeruk\\n\"\r\n    \"-1 batang serai, memarkan\\n\"\r\n    \"-200 ml air\\n\"\r\n    \"-100 ml santan kental\\n\\n\"\r\n\r\n\r\n    \"Bumbu Halus\\n\"\r\n    \"-4 butir bawang merah\\n\"\r\n    \"-2 siung bawang putih\\n\"\r\n    \"-150 gr cabai hijau \\n\"\r\n    \"-5 buah cabe rawit hijau besar\\n\"\r\n    \"-2 cm jahe\\n\"\r\n    \"-2 cm kunyit\\', '\"Cara Membuat\\n\\n\"\r\n    \"1. Lumuri potongan ayam dengan air jeruk nipis, diamkan selama 30 menit.\\n\"\r\n    \"2. Panaskan minyak Goreng ayam, Tumis seluruh bumbu halus hingga harum, tambahkan serai, daun jeruk dan asam kandis, masak hingga bumbu matang.\\n\"\r\n    \"3. Masukkan daging bebek, masak hingga bebek setengah matang. Tuang air dan santan.\\n\"\r\n    \"4. Masak dengan api kecil hingga bebek matang dan kuah berminyak. Angkat.\\n\"\r\n', 'bbkcbeijo.jpg'),
(4, 'Bacem Bebek', '\" Bacem bebek bisa bertahan selama tiga harijika disimpan di dalam freezer. Anda bisa memanasinya ketika akan dihidangkan lagi. Saat menghidangkan jangan Iupa untuk memmisahkan daun salam, Iengkuas dan jahe agar tampilan lebih bersih dan rapi\"', '\"Bahan Utama:\\n\"\r\n    \"-1 ekor bebek, cuci bersih, potong 8 bagian\\n\"\r\n    \"-2 sdm air jeruk nipis\\n\"\r\n    \"-2 Iembar daun salam \\n\"\r\n    \"-1 500 ml air kelapa \\n\"\r\n    \"-2 batang serai, memarkan\\n\"\r\n    \"-50 ml air\\n\"\r\n    \"-100 ml santan kental\\n\\n\"\r\n\r\n\r\n    \"Bumbu Halus\\n\"\r\n    \"-5 butir bawang merah\\n\"\r\n    \"-6 siung bawang putih\\n\"\r\n    \"-2 sdt ketumbar\\n\"\r\n    \"-2 cm lengkuas\\n\"\r\n    \"-1 sdt garam\\n\"\r\n    \"-100 gr gula merah\\n\\n\"', '\"Cara Membuat\\n\\n\"\r\n    \"1. Rendam daging bebek dengan airjeruk nipis, dan garam.\\n\"\r\n    \"2. Masak daging bebek dengan air kelapa, bumbu halus, daun salam, lengkuas, serai, dan jahe sampai matang dan empuk.\\n\"\r\n    \"3. Goreng bebek sampai kecokelatan. Angkat dan sajikan.\\n\"', 'bbkbcm.jpg'),
(5, 'Asam-asam Iga', '\" Rasa pedas, asam dan gurih nya iga menjadikan tidak hanya mudah disantap tetapi juga Iezat dilidah. Masakan siap dinikmati selagi masih panas atau hangat. Tidak terlalu rumit resep asam-asam iga ini, bukan? Selamat berkreasi.\"', '\"Bahan Bahan:\\n\"\r\n    \"-2 sendok makan minyak goreng \\n\"\r\n    \"-2 siung bawang putih, iris-iris n\"\r\n    \"-2 Iembar daun salam \\n\"\r\n    \"-5 siung bawang merah, iris-iris \\n\"\r\n    \"-2 buah cabai merah, potong-potong 1 jari 3 buah cabai hijau, potong-potong 1 jari \\n\"\r\n    \"-1 kg iga sapi, potong-potong dan biarkan daging masih melekat di tulangnya \\n\"\r\n    \"-1 buah tomat, potong melintang \\n\"\r\n    \"-4 buah belimbing sayur, belah dua \\n\"\r\n    \"-Garam dan merica secukupnya \\n\"\r\n    \"-2 cm lengkuas, ', '\"Cara Membuat\"', 'asamiga.jpg'),
(6, 'Beef Teriyaki', '\" Beef teriyaki salah satu olahan daging sapi khas Jepang dengan campuran bumbu teriyaki yang manis juga gurih. Langsung saja ulik resepnya dan praktek di dapur rumah Anda. Selamat mencoba.\\n\\n\"', '\"Bahan Bahan:\\n\"\r\n    \"-150 gram daging has Iuar, iris tipis-tipis \\n\"\r\n    \"-1 sdt air jahe n\"\r\n    \"-1 sdt kecap asin \\n\"\r\n    \"-1 sdt merica bubuk \\n\"\r\n    \"-1 sdt angciu \\n\"\r\n    \"-1 sdm gula merah 4 sdm minyak goreng \\n\"\r\n    \"-1 buah bawang Bombay, iris bulat \\n\"\r\n    \"-iris bulat 1/2 buah paprika hijau, potong bentuk korek api \\n\"\r\n    \"-1 sdt gula pasir \\n\"\r\n    \"-50 ml air mendidih \\n\"\r\n    \"-50 gram Acar Lobak dan Wortel \\n\"\r\n    \"-1/2 sdt cuka \\n\"\r\n    \"-1/2 sdt garam \\n\\n\"', '\"Cara Membuat\\n\\n\"\r\n    \"1. Campur daging iris dengan airjahe, kecap asin, merica, angciu, dan gula merah, aduk rata. Diamkan 30 menit.\\n\"\r\n    \"2. Sementara itu, panaskan minyak goreng, tumis bawang merah dan bawang putih sampai harum; \\n\"\r\n    \"3. Panaskan gula pasir, masakn hingga kecokelatan. Siram dengan air mendidih, aduk dan Sisihkan; \\n\"\r\n    \"4. Panaskan 2 sdm minyak goreng, masukkan daging bern=bumbu selembar demi selembar. Setelah berubah warna, masukkan tumisan bawang Bombay dan papr', 'beefteriyaki.jpg'),
(7, 'Bala-Bala Teri', '\"Bala-bala teri sayuran ini sangat pas sebagai teman makan nasi atau sekedar untuk camilan. Sajikan bersama teh hangat dan jangan lupa nikmati bersama cabe rawit. Selamat berkreasi.\"', '\"Bahan Bahan:\\n\"\r\n    \"-200 gram teri nasi basah, cuci bersih \\n\"\r\n    \"-1 batang daun bawang, iris halus \\n\"\r\n    \"-1 buah wortel, potong ala korek api  \\n\"\r\n    \"-1 butir telur \\n\"\r\n    \"-100 gram tepung terigu \\n\"\r\n    \"-3 sdm air \\n\"\r\n    \"-2 sdm tepung beras \\n\"\r\n    \"-Penyedap rasa secukupnya (bila suka) Garam secukupnya \\n\"\r\n    \"-Minyak Goreng \\n\"\r\n    \"-1 butir bawang merah, haluskan \\n\"\r\n    \"-1 butir kemiri, haluskan  \\n\"\r\n    \"-l sdm ketumbar sangrai, haluskan \\n\"\r\n    \"-2 cm kunyit,', '\"Cara Membuat\\n\\n\"\r\n    \"1. Campurkan semua bahan, kecuali minyak goreng, menjadi satu, aduk rata \\n\"\r\n    \"2. Bentuk adonan bulat dengan bantuan 2 buah sendok makan; \\n\"\r\n\r\n    \"3. Masukkan ke dalam minyak panas, goreng dengan api yang \r\nsedang, bolak balik bala bala hingga kecoklatan, angkat dan tiriskan.\\n\\n\"', 'balateri.jpg'),
(8, 'Balado Teri', '\"Banyak pilihan ikan asin yang bisa digunakan, dalam resep ini kami memnggunakan ikan asin kipas. Sebagai alternatif, anda bisa saja menggunakan teri medan atau jenis teri Iainnya. Untuk menghilangkan rasa asin yang berlebihan pada teri, anda bisa merendamnya terlebih dahulu dengan air hangat selama beberapa menit sebelum digoreng kering. Semoga resep balado teri yang kami sajikan ini bisa menjadi favorit anda. Selamat mencoba.\\n\\n\"', '\"Bahan Bahan:\\n\"\r\n    \"-250 gram ikan asin kipas\\n\"\r\n    \"-5 cabai merah  n\"\r\n    \"-2 siung bawang putih  \\n\"\r\n    \"-4 siung bawang merah \\n\"\r\n    \"-1 sdt garam \\n\"\r\n    \"-3 sdm air asam jawa \\n\"\r\n    \"-1 cm lengkuas, memarkan \\n\"\r\n    \"-2 Iembar daun salam  \\n\"\r\n    \"-2 sdm gula pasir \\n\"\r\n    \"-2 200 ml minyak goreng \\n\\n\"', '\"Cara Membuat\\n\\n\"\r\n    \"1. Panaskan minyak goreng, goreng ikan asin kipas hingga kering dan berwarna kecokelatan. Sisihkan. \\n\"\r\n    \"2. Haluskan bawang merah, bawng putih, cabai merah dan garam. Tumis bumbu halus hingga harum. Masukkan air asam jawa, lengkuas, daun salam. Masak hingga bumbu mengental. \\n\"\r\n    \"3. Masukkan ikan asin yang sudah di goreng. Aduk rata perlahan hingga bumbu tercampur rata. Angkat, sajikan.\\n\\n\"', 'baladoteri.jpg'),
(9, 'Cumi Goreng Tepung', '\"Cumi goreng tepung yang enak adalah cumi tidak alot dan tepung terasa gurih serta renyah. Karena itu diperlukan paduan beberapa macam tepung dan juga tambahan sedikit baking soda agar gorengan tepung bisa mengembang.\"', '\" Bahan: \"\r\n\"300 gram cumi segar\"\r\n\"1 buah jeruk nipis, peras airnya\"\r\n\"1 sdt garam\"\r\n\"1/2 sdt merica bubuk\"\r\n\"3 sdm tepung terigu\"\r\n\"1sdm tepung beras\"\r\n\"1 sdm tepung tapioca\"\r\n\"1/4 sdt baking powder\"\r\n\"1 butir telur, kocok lepas\"\r\n\"minyak goreng secukupnya\"\r\n\"Mayonaise\"\r\n\"Saus tomat\"\r\n\"Saus sambal\"', '\"Cara membuat\"\r\n\"Bersihkan cumi dan kupas kulitnya, kemudian potong bulat 1/2cm\"\r\n\"Lumuri cumi dengan air jeruk nipis\"\r\n\"Tambahkan garam dan merica, aduk hingga tercampur rata\"\r\n\"Campur tepung terigu, tepung beras dan tepung tapioka, aduk rata\"\r\n\"Gulingkan cumi dalam campuran tepung hingga merata\"\r\n\"Celupkan ke telur kocok, angkat\"\r\n\"Gulingkan kembali ke dalam campuran tepung hingga tertutup merata, angkat dan sisihkan\"\r\n\"Panaskan minyak dan goreng cumi hingga matang berwarna keemasan\"\r\n\"Hidangk', 'cumigoreng.jpg'),
(10, 'Pindang Baso Ikan', '\"Ciri khas bentuk bulat seperti bola membuat bakso dikenal sebagai makanan yang populer di mana-mana. Bahan yang paling lazim digunakan adalah daging sapi, nah kali ini bakso akan dibuat dengan bahan perpaduan antara ikan tenggiri dan udang. Ikan Tenggiri adalah ikan yang memiliki kandungan gizi cukup tinggi, sehingga ikan ini sering kali dipilih menjadi bahan makanan olahan ikan.\"', '\"Bahan-bahan: \"\r\n\"300 gram ikan tenggiri, haluskan\"\r\n\"200 gram udang, kupas, haluskan\"\r\n\"3 sendok makan tepung sagu\"\r\n\"1 butir telur\"\r\n\"1 batang daun bawang, iris tipis\"\r\n\"Garam, merica bubuk, gula pasir secukupnya\"\r\n\"Bumbu yang dihaluskan: \"\r\n\"3 siung bawang putih, iris tipis\"\r\n\"7 butir bawang merah, iris tipis\"\r\n\"3 buah cabai merah, iris tipis\"\r\n\"2 cm kunyit, haluskan\"\r\n\"3 sendok makan minyak goreng\"\r\n\"2 cm lengkuas, memarkan\"\r\n\"2 cm jahe, memarkan\"\r\n\"2 lembar daun salam\"\r\n\"3 buah tomat hijau,', '\"Cara membuat: \"\r\n\"Campur semua bahan bakso, aduk hingga rata; \"\r\n\"Ambil satu sendok teh adonan, bulatkan. Rebus ke dalam air mendidih hingga matang dan mengapung. Angkat dan ditiriskan; \"\r\n\"Panaskan minyak, tumis bumbu halus, lengkuas, jahe dan daun salam hingga harum; \"\r\n\"Masukkan tomat, belimbing, daun bawang, garam, merica, gula pasir, bakso ikan. Masak hingga bumbu meresap. \"', 'pinsokan.jpg'),
(11, 'Orek Tempe', '\"Tempe berasal dari kedelai yang kaya akan vitamin A, B, dan E, serta berbagai macam mineral yang baik bagi tubuh. Dengan asupan gizi yang baik, tentu tubuh tidak akan terasa lemas meski tidak mendapatkan asupan makanan selama lebih dari 14 jam.\"\r\n\r\n\"Tempe dipercaya banyak mengandung HDL, kolesterol yang ramah bagi pembuluh darah. JUga mengandung banyak serat yang tentunya bagus bagi pencernaan.\"', '\"Bahan-bahan\"\r\n\"500 gram tempe, potong dadu, goreng setengah matang\"\r\n\"4 buah cabai hijau, iris serong\"\r\n\"4 buah cabai merah, iris serong\"\r\n\"2 siung bawang putih, iris tipis\"\r\n\"4 butir bawang merah, iris tipis\"\r\n\"2 cm lengkuas\"\r\n\"2 lembar daun salam\"\r\n\"1 sdm kecap manis\"\r\n\"1 sdt garam\"\r\n\"1/2 sdt terasi\"\r\n\"50 ml air\"\r\n\"2 sdm minyak untuk menumis\"', '\"Cara membuat\"\r\n\r\n\"Panaskan minyak goreng, tumis semua bumbu iris hingga layu, tumis terus hingga keluar aroma harum. \"\r\n\r\n\"Masukkan tempe yang sudah digoreng, tambahkan kecap manis dan air. Masak dalam api kecil hingga kecap meresap ke dalam tempe. \"\r\n\r\n\"Sajikan hangat. \"\r\n', 'orektempe.jpg'),
(12, 'Sate Lilit Bali', '\"Sate Lilit adalah sebuah varian sate asal Bali. Sate ini terbuat dari daging babi, ikan, ayam, daging sapi, atau bahkan kura-kura yang dicincang, kemudian dicampur dengan parutan kelapa, santan, jeruk nipis, bawang merah, dan merica. Daging cincang yang telah berbumbu dilekatkan pada sebuah bambu atau tebu, kemudian dipanggang di atas arang. \"', '\"Bahan : \"\r\n\"- 100 gr kelapa parut. \"\r\n\"- 300 gr daging ayam (giling). \"\r\n\"- 1 butir telur ayam. \"\r\n\"- 2 sdm tapioka. \"\r\n\"- 4 siung bawang putih. \"\r\n\"- 5 siung bawang merah. \"\r\n\"- 3 biji kemiri (sangrai). \"\r\n\"- 1 cm lengkuas. \"\r\n\"- 1 cm jahe. \"\r\n\"- 1 cm kunyit (bakar). \"\r\n\"- 2 cm kencur. \"\r\n\"- 1 cm terasi (bakar). \"\r\n\"- 20 batang bambu atau serai. \"\r\n\"- 5 buah cabe rawit (boleh lebih). \"\r\n\"- garam & merica secukupnya . \"', '\"Cara memasak : \"\r\n\"a. Haluskan bawang merah,bawang putih, kunyit, cabai, kemiri, jahe, kencur, lengkuas dan terasi. \"\r\n\"b. Campurkan ayam giling,telur,tapioka,dan kelapa. Beri garam dan merica secukupnya. \"\r\n\"c. Tumis bumbu halus hingga harum lalu campurkan kedalam adonan daging ayam. Aduk rata. \"\r\n\"d. Panaskan Grill Pan dengan api sedang. Ambil sedikit adonan. Masak hingga matang. Lalu cicipi rasanya hingga pas. \"\r\n\"e. Jika rasa sudah pas. Ambil adonan secukupnya dan lilitkan pada batang Bambu', 'satelilit.jpg'),
(13, 'Gudeg Pedas Manis', '\"Gudeg (ejaan bahasa Jawa: Gudheg) adalah makanan khas Provinsi Yogyakarta dan Jawa Tengah yang terbuat dari nangka muda yang dimasak dengan santan. Perlu waktu berjam-jam untuk membuat masakan ini. Warna coklat biasanya dihasilkan oleh daun jati yang dimasak bersamaan. Gudeg dimakan dengan nasi dan disajikan dengan kuah santan kental (areh), ayam kampung, telur, tempe, tahu dan sambal goreng krecek. \"', '\"Bahan-bahan\"\r\n\"1/2 ekor ayam kampung\"\r\n\"4 bh telur rebus\"\r\n\"1 buah nangka muda (700 grm) \"\r\n\"1 liter santan kental\"\r\n\"Bumbu : \"\r\n\"4 bawang putih\"\r\n\"6 bawang merah\"\r\n\"10 cabe merah keriting\"\r\n\"5 kemiri\"\r\n\"1 sdt ketumbar\"\r\n\"1 ruas laos\"\r\n\"1 serai\"\r\n\"2 lembarr daun salam\"\r\n\"5 daun jati (ambil pucuk daun) \"\r\n\"1 gula merah\"\r\n\"Garam, gula\"', '\"Cara Membuat\"\r\n\"- Potong dan rebus nangka sampai setengah matang, beri garam untuk hilangin getah. \"\r\n\"- Haluskan bumbu, kecuali laos dan serai digeprek. \"\r\n\"- Siapkan panci, letakkan daun jati 2 lbr dibawah nangka, ayam, bumbu dan santan. Diatas taruh 3 lbr daun jati. Beri garam, gula sesuai selera (manis disesuaikan yah). \"\r\n\"- Masak dengan api kecil, sesekali diaduk. Setelah hampir matang masukkan telur dan masak kembali sampai kuah mengering. \"\r\n\"- Lama masak tergantung dari banyak sedikit ', 'gudegpedesmanis.jpg'),
(14, 'Pempek Palembang', '\"Pempek atau empek-empek adalah makanan khas Palembang yang terbuat dari daging ikan yang digiling lembut dan tepung kanji (secara salah kaprah sering disebut sebagai \"tepung sagu\"), serta beberapa komposisi lain seperti telur, bawang putih yang dihaluskan, penyedap rasa dan garam. Sebenarnya sulit untuk mengatakan bahwa penganan pempek pusatnya adalah di Palembang karena hampir semua daerah di Sumatera Selatan memproduksinya. \"', '\"Bahan untuk biang : \"\r\n\"- 200 gr terigu. \"\r\n\"- 400 ml air. \"\r\n\"- Garam dan gula Secukupnya. \"\r\n\"Bahan untuk adonan pempek : \"\r\n\"- 5 siung bawang putih dihaluskan. \"\r\n\"- 3 butir telur dikocok (dicampur ke dalam adonan pempek). \"\r\n\"- 400 gr sagu tani. \"\r\n\"Bahan untuk isian : \"\r\n\"- 2 butir telur dikocok beri sedikit garam dan gula. \"', '\"Cara memasak : \"\r\n\"a. Dalam panci campur terigu, air, garam dan gula. Aduk rata. Nyalakan api, masak sambil diaduk-aduk sampai menggumpal seperti bubur (hati-hati gosong) Angkat. Biarkan hangat. \"\r\n\"b. Pindahkan biang yang sudah tidak panas ke dalam baskom. Dalam keadaan hangat tambahkan bawang putih, telur kocok. Aduk rata pakai sendok kayu. \"\r\n\"c. Masukkan sagu sedikit-sedikit. Aduk rata. \"\r\n\"d. Balur tangan dengan sagu, ambil sebagian adonan bentuk silinder\"\r\n\"e.Buat lubang dengan menggunaka', 'pempek.jpg'),
(15, 'Soto Kuning Ayam', '\"Masakan Nusantara Indonesia berkuah kuning ini cocok dinikmati saat udara dingin. Soto kuning dengan paduan suwiran ayam hingga suun serta tauge.\"', '\"Bahan: \"\r\n\"1/2 ekor ayam negeri, potong dua\"\r\n\"1 liter air\"\r\n\"2 sdm minyak sayur\"\r\n\"1 batang serai, memarkan\"\r\n\"2 lembar daun salam\"\r\n\"2 lembar daun jeruk\"\r\n\"Bumbu Halus: \"\r\n\"4 butir kemiri\"\r\n\"3 cm kunyit\"\r\n\"1 cm jahe\"\r\n\"5 butir bawang putih\"\r\n\"3 siung bawang merah\"\r\n\"1/2 sdt merica butiran\"\r\n\"2 sdt garam\"\r\n\"Pelengkap: \"\r\n\"Tauge\"\r\n\"Suun\"\r\n\"Telur rebus\"\r\n\"Daun bawang\"\r\n\"Bawang merah goreng\"\r\n\"Jeruk Nipis\"', '\"Cara Membuat: \"\r\n\"- Didihkan air, rebus ayam dengan api kecil hingga hampir lunak. \"\r\n\"- Tumis bumbu halus bersama daun jeruk, daun salam, serai dan aduk hingga wangi. Angkat. \"\r\n\"- Masukkan ke dalam rebusan ayam. \"\r\n\"- Rebus dengan api kecil hingga daging ayam lunak. Angkat ayam, tiriskan. \"\r\n\"- Suwir daging ayam kasar-kasar. \"\r\n\"- Susun ayam, suun, tauge dalam mangkuk saji. \"\r\n\"- Tuangi kaldu panas dan sajikan dengan daun bawang, baang goreng, dan jeruk nipis. \"', 'sotoayam.jpg'),
(16, 'Ayam Lodho', '\"Ayam lodho ini merupakan masakan Nusantara Jawa Timur, khas Tulungagung. Ayam yang sudah dipanggang kemudian dicampurkan dengan santan dan bumbu. Rasa gurihnya medhok dan mantap.\"', '\"Bahan: \"\r\n\"1 ekor ayam kampung\"\r\n\"1 butir kelapa, kupas, parut, ambil 250 ml santan kental dan 500 ml santan encer\"\r\n\"Haluskan: \"\r\n\"10 butir bawang merah\"\r\n\"10 siung bawang putih\"\r\n\"3 (5 cm)ruas jari kunyit\"\r\n\"2 (4 cm) ruas jari jahe\"\r\n\"1 (2 cm) ruas jari kencur\"\r\n\"2 cabai merah keriting, rebus\"\r\n\"2 sdt garam\"\r\n\"Bumbu Kasar: \"\r\n\"1 sdm merica butiran, tumbuk kasar\"\r\n\"1 sdm ketumbar, tumbuk kasar\"\r\n\"1 sdt jintan\"\r\n\"100 g cabai rawit\"\r\n\"1 jempol (3 cm) lengkuas, iris kasar\"\r\n\"3 batang serai, memar', '\"Cara membuat: \"\r\n\"- Belah ayam dari bagian dada depan ke bawah, lalu bentangkan ayam hingga terbuka lebar. \"\r\n\"- Lumuri garam dan bakar di atas bara api hingga setengah matang. \"\r\n\"- Tumis bumbu kasar hingga wangi. \"\r\n\"- Masukkan bumbu halus, aduk hingga wangi dan matang. \"\r\n\"- Tambahkan santan encer ke dalam tumisan, didihkan. \"\r\n\"- Masukkan ayam bakar ke dalam wajan, tambahkan serai, daun salam dan daun jeruk purut. \"\r\n\"- Teruskan memasak dengan api kecil sampai mendidih. \"\r\n\"- Tambahkan sant', 'ayamlodho.jpg'),
(17, 'Rendang Padang', '\"Makanan Nusantara yang satu ini banyak memiliki penggemar. Rendang Padang dengan bumbu cokelat kehitaman yang gurih memiliki rasa nikmat. Mau tahu resepnya?\"', '\"Bahan: \"\r\n\"1 kg daging sapi\"\r\n\"3 butir kelapa, diambil santan kental dan santan encernya\"\r\n\"4 lembar daun jeruk\"\r\n\"3 batang serai, memarkan\"\r\n\"4 butir asam kandis\"\r\n\"100ml minyak goreng\"\r\n\"5 gram garam\"\r\n\"Bumbu: \"\r\n\"60 g bawang merah\"\r\n\"50 g bawang putih\"\r\n\"250 g cabai merah besar\"\r\n\"100 g lengkuas\"\r\n\"50 g kemiri\"\r\n\"2 g cengkeh\"', '\"Cara membuat : \"\r\n\"- Haluskan semua bahan Bumbu dengan diulek atau dblender. \"\r\n\"- Tumis bumbu dengan sedikit minyak goreng hingga wangi. \"\r\n\"- Masukkan batang serai, daun jeruk, asam kandis dan garam, aduk rata. \"\r\n\"- Tuangi santan dan dididihkan, masukkan daging. \"\r\n\"- Masak dengan api kecil selama beberapa jam sampai daging empuk dan bumbu kecoklatan sesuai selera. \"', 'rendangpadang.jpg'),
(18, 'Sate Ayam Madura', '\"Sate Ayam Madura\"', '\"Bahan-bahan untuk 25 tusuk : \"\r\n\"250 gram dada ayam\"\r\n\"1 sdm air jeruk nipis\"\r\n\"1/4 sdt garam\"\r\n\"Bahan bumbu : \"\r\n\"100 gram kacang (digoreng) \"\r\n\"2-3 buah bawang putih\"\r\n\"2 buah bawang merah\"\r\n\"3 buah kemiri (disangrai) \"\r\n\"1/2 sdt merica bubuk\"\r\n\"150 ml air (secukupnya sampai kekentalannya pas) \"\r\n\"3 sdm kecap\"\r\n\"1 sdm gula merah\"\r\n\"1/4 sdt garam (secukupnya) \"\r\n\"3 sdm minyak/secukupnya (untuk menumis) \"\r\n\"Bahan Pelengkap : \"\r\n\"Secukupnya bawang goreng\"\r\n\"Secukupnya bawang merah (iris tipis) \"', '\"Langkah langkah \"\r\n\"Cuci ayam sampai bersih, potong berbentuk dadu. Lumuri ayam dengan jeruk nipis dan garam. Tusukkan ayam pada tusuk sate. \"\r\n\"Haluskan semua bahan bumbu(saya bahannya dihaluskan pakai chopper/diulek,trus ditambah air. bisa jg diblender sih, teksturnya lbh halus). \"\r\n\"Tumis bumbu dengan minyak sambil diaduk hingga mengental. Matikan api. \"\r\n\"Ambil 3 sdm bumbu, tambahkan 1 sdm kecap dan 1 sdm air sebagai bahan celupan sebelum dibakar.biarkan selama minimal 20 menit agar bumbu m', 'satemadura.jpg');

-- --------------------------------------------------------

--
-- Stand-in struktur untuk tampilan `menu`
-- (Lihat di bawah untuk tampilan aktual)
--
CREATE TABLE `menu` (
`Nama` varchar(20)
,`pendahuluan` varchar(500)
,`Resep` varchar(500)
,`Cara` varchar(500)
,`foto` varchar(255)
);

-- --------------------------------------------------------

--
-- Struktur untuk view `menu`
--
DROP TABLE IF EXISTS `menu`;

CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `menu`  AS  select `masakan`.`Nama` AS `Nama`,`masakan`.`pendahuluan` AS `pendahuluan`,`masakan`.`Resep` AS `Resep`,`masakan`.`Cara` AS `Cara`,`masakan`.`foto` AS `foto` from `masakan` ;

--
-- Indexes for dumped tables
--

--
-- Indeks untuk tabel `masakan`
--
ALTER TABLE `masakan`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT untuk tabel yang dibuang
--

--
-- AUTO_INCREMENT untuk tabel `masakan`
--
ALTER TABLE `masakan`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=19;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
